/// ISO 3166-1 alpha-2 → international dialing code (no +).
const Map<String, String> kCountryDialCodes = {
  'AF': '93',
  'AL': '355',
  'DZ': '213',
  'AR': '54',
  'AU': '61',
  'AT': '43',
  'BH': '973',
  'BD': '880',
  'BE': '32',
  'BR': '55',
  'CA': '1',
  'CN': '86',
  'CO': '57',
  'DK': '45',
  'EG': '20',
  'FI': '358',
  'FR': '33',
  'DE': '49',
  'GH': '233',
  'GR': '30',
  'HK': '852',
  'HU': '36',
  'IN': '91',
  'ID': '62',
  'IQ': '964',
  'IE': '353',
  'IL': '972',
  'IT': '39',
  'JP': '81',
  'JO': '962',
  'KE': '254',
  'KW': '965',
  'MY': '60',
  'MV': '960',
  'MX': '52',
  'NP': '977',
  'NL': '31',
  'NZ': '64',
  'NG': '234',
  'NO': '47',
  'OM': '968',
  'PK': '92',
  'PH': '63',
  'PL': '48',
  'PT': '351',
  'QA': '974',
  'RO': '40',
  'RU': '7',
  'SA': '966',
  'SG': '65',
  'ZA': '27',
  'KR': '82',
  'ES': '34',
  'LK': '94',
  'SE': '46',
  'CH': '41',
  'TW': '886',
  'TH': '66',
  'TR': '90',
  'AE': '971',
  'GB': '44',
  'US': '1',
  'VN': '84',
};

const Map<String, String> kCountryNames = {
  'BD': 'Bangladesh',
  'IN': 'India',
  'PK': 'Pakistan',
  'US': 'United States',
  'GB': 'United Kingdom',
  'AE': 'United Arab Emirates',
  'SA': 'Saudi Arabia',
  'MY': 'Malaysia',
  'SG': 'Singapore',
  'AU': 'Australia',
  'CA': 'Canada',
  'NP': 'Nepal',
  'LK': 'Sri Lanka',
  'ID': 'Indonesia',
  'PH': 'Philippines',
  'TH': 'Thailand',
  'TR': 'Turkey',
  'DE': 'Germany',
  'FR': 'France',
  'IT': 'Italy',
  'ES': 'Spain',
  'NL': 'Netherlands',
  'JP': 'Japan',
  'CN': 'China',
  'KR': 'South Korea',
  'QA': 'Qatar',
  'KW': 'Kuwait',
  'BH': 'Bahrain',
  'OM': 'Oman',
  'EG': 'Egypt',
  'NG': 'Nigeria',
  'ZA': 'South Africa',
  'BR': 'Brazil',
  'MX': 'Mexico',
  'NZ': 'New Zealand',
  'IE': 'Ireland',
  'SE': 'Sweden',
  'NO': 'Norway',
  'DK': 'Denmark',
  'CH': 'Switzerland',
  'AT': 'Austria',
  'BE': 'Belgium',
  'PL': 'Poland',
  'PT': 'Portugal',
  'RO': 'Romania',
  'HU': 'Hungary',
  'GR': 'Greece',
  'IL': 'Israel',
  'JO': 'Jordan',
  'IQ': 'Iraq',
  'AF': 'Afghanistan',
  'MV': 'Maldives',
  'VN': 'Vietnam',
  'HK': 'Hong Kong',
  'TW': 'Taiwan',
  'RU': 'Russia',
  'KE': 'Kenya',
  'GH': 'Ghana',
  'AR': 'Argentina',
  'CO': 'Colombia',
  'FI': 'Finland',
  'AL': 'Albania',
  'DZ': 'Algeria',
};

String dialCodeForIso(String iso, {String fallback = '880'}) {
  return kCountryDialCodes[iso.toUpperCase()] ?? fallback;
}

String countryNameForIso(String iso) {
  final code = iso.toUpperCase();
  return kCountryNames[code] ?? code;
}
